import {
  ArrowDown,
  ArrowUp,
  ArrowUpDown,
  FileSpreadsheet,
  FileText,
  MoreHorizontal,
  Users,
} from "lucide-react";

import type {
  Report,
} from "../reportsData";

type SortField =
  | "name"
  | "category"
  | "createdAt"
  | "status"
  | "format";

type SortDirection = "asc" | "desc";

type ReportsTableProps = {
  reports: Report[];
  sortField: SortField;
  sortDirection: SortDirection;
  onSort: (field: SortField) => void;
  onReportClick: (report: Report) => void;
};

const STATUS_STYLES: Record<
  Report["status"],
  {
    background: string;
    text: string;
    dot: string;
  }
> = {
  Ready: {
    background: "bg-[#E8F8F1]",
    text: "text-[#087443]",
    dot: "bg-[#12B76A]",
  },

  Generating: {
    background: "bg-[#EAF2FF]",
    text: "text-[#1355B5]",
    dot: "bg-[#1677FF]",
  },

  Scheduled: {
    background: "bg-[#F2EDFF]",
    text: "text-[#6941C6]",
    dot: "bg-[#7F56D9]",
  },

  Failed: {
    background: "bg-[#FEF3F2]",
    text: "text-[#B42318]",
    dot: "bg-[#F04438]",
  },

  Archived: {
    background: "bg-[#F2F4F7]",
    text: "text-[#475467]",
    dot: "bg-[#98A2B3]",
  },
};

function SortIcon({
  field,
  activeField,
  direction,
}: {
  field: SortField;
  activeField: SortField;
  direction: SortDirection;
}) {
  if (field !== activeField) {
    return (
      <ArrowUpDown className="h-3 w-3 text-[#98A2B3]" />
    );
  }

  return direction === "asc" ? (
    <ArrowUp className="h-3 w-3 text-[#1677FF]" />
  ) : (
    <ArrowDown className="h-3 w-3 text-[#1677FF]" />
  );
}

function TableHeader({
  children,
  field,
  activeField,
  direction,
  onSort,
}: {
  children: React.ReactNode;
  field: SortField;
  activeField: SortField;
  direction: SortDirection;
  onSort: (field: SortField) => void;
}) {
  return (
    <th
      scope="col"
      className="whitespace-nowrap px-4 py-3 text-left"
    >
      <button
        type="button"
        onClick={() => onSort(field)}
        className="group inline-flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[0.08em] text-[#667085] transition hover:text-[#344054]"
      >
        {children}

        <SortIcon
          field={field}
          activeField={activeField}
          direction={direction}
        />
      </button>
    </th>
  );
}

function formatDate(
  value: string,
) {
  return new Intl.DateTimeFormat(
    "en-US",
    {
      month: "short",
      day: "numeric",
      year: "numeric",
    },
  ).format(
    new Date(
      `${value}T00:00:00`,
    ),
  );
}

export function ReportsTable({
  reports,
  sortField,
  sortDirection,
  onSort,
  onReportClick,
}: ReportsTableProps) {
  return (
    <div className="overflow-hidden rounded-xl border border-[#E4E7EC] bg-white shadow-[0_1px_2px_rgba(16,24,40,0.04)]">
      <div className="flex items-center justify-between border-b border-[#E4E7EC] px-5 py-4">
        <div>
          <h3 className="text-sm font-semibold text-[#172033]">
            Reports
          </h3>

          <p className="mt-0.5 text-[11px] text-[#667085]">
            {reports.length}{" "}
            {reports.length === 1
              ? "report"
              : "reports"}{" "}
            displayed
          </p>
        </div>

        <div className="flex items-center gap-2 text-[10px] text-[#98A2B3]">
          <span className="h-2 w-2 rounded-full bg-[#12B76A]" />

          Reporting center
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="min-w-[1180px] w-full border-collapse">
          <thead className="border-b border-[#E4E7EC] bg-[#F9FAFB]">
            <tr>
              <TableHeader
                field="name"
                activeField={sortField}
                direction={sortDirection}
                onSort={onSort}
              >
                Report
              </TableHeader>

              <TableHeader
                field="category"
                activeField={sortField}
                direction={sortDirection}
                onSort={onSort}
              >
                Category
              </TableHeader>

              <th
                scope="col"
                className="whitespace-nowrap px-4 py-3 text-left"
              >
                <span className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#667085]">
                  Period
                </span>
              </th>

              <th
                scope="col"
                className="whitespace-nowrap px-4 py-3 text-left"
              >
                <span className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#667085]">
                  Generated By
                </span>
              </th>

              <TableHeader
                field="createdAt"
                activeField={sortField}
                direction={sortDirection}
                onSort={onSort}
              >
                Created
              </TableHeader>

              <TableHeader
                field="format"
                activeField={sortField}
                direction={sortDirection}
                onSort={onSort}
              >
                Format
              </TableHeader>

              <TableHeader
                field="status"
                activeField={sortField}
                direction={sortDirection}
                onSort={onSort}
              >
                Status
              </TableHeader>

              <th
                scope="col"
                className="whitespace-nowrap px-4 py-3 text-left"
              >
                <span className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#667085]">
                  Recipients
                </span>
              </th>

              <th
                scope="col"
                className="w-12 px-4 py-3"
              >
                <span className="sr-only">
                  Actions
                </span>
              </th>
            </tr>
          </thead>

          <tbody className="divide-y divide-[#E4E7EC]">
            {reports.map(
              (report) => {
                const statusStyle =
                  STATUS_STYLES[
                    report.status
                  ];

                return (
                  <tr
                    key={report.id}
                    onClick={() =>
                      onReportClick(
                        report,
                      )
                    }
                    className="group cursor-pointer bg-white transition hover:bg-[#F9FAFB]"
                  >
                    <td className="px-4 py-3">
                      <div className="flex items-center gap-3">
                        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-[#EAF2FF]">
                          {report.format ===
                          "Excel" ? (
                            <FileSpreadsheet className="h-3.5 w-3.5 text-[#1677FF]" />
                          ) : (
                            <FileText className="h-3.5 w-3.5 text-[#1677FF]" />
                          )}
                        </div>

                        <div className="min-w-0">
                          <div className="truncate text-xs font-semibold text-[#172033]">
                            {report.name}
                          </div>

                          <div className="mt-0.5 truncate text-[10px] text-[#98A2B3]">
                            {
                              report.reportNumber
                            }
                          </div>
                        </div>
                      </div>
                    </td>

                    <td className="px-4 py-3">
                      <span className="inline-flex whitespace-nowrap rounded-md bg-[#F2F4F7] px-2 py-1 text-[10px] font-medium text-[#475467]">
                        {report.category}
                      </span>
                    </td>

                    <td className="px-4 py-3">
                      <div className="whitespace-nowrap text-xs font-medium text-[#344054]">
                        {formatDate(
                          report.periodStart,
                        )}
                      </div>

                      <div className="mt-0.5 whitespace-nowrap text-[10px] text-[#98A2B3]">
                        to{" "}
                        {formatDate(
                          report.periodEnd,
                        )}
                      </div>
                    </td>

                    <td className="px-4 py-3">
                      <div className="whitespace-nowrap text-xs font-medium text-[#344054]">
                        {
                          report.generatedBy
                        }
                      </div>
                    </td>

                    <td className="px-4 py-3">
                      <div className="whitespace-nowrap text-xs font-medium text-[#344054]">
                        {formatDate(
                          report.createdAt,
                        )}
                      </div>
                    </td>

                    <td className="px-4 py-3">
                      <span className="inline-flex rounded-md border border-[#E4E7EC] bg-white px-2 py-1 text-[10px] font-semibold text-[#475467]">
                        {report.format}
                      </span>
                    </td>

                    <td className="px-4 py-3">
                      <span
                        className={`inline-flex items-center gap-1.5 whitespace-nowrap rounded-full px-2.5 py-1 text-[10px] font-semibold ${statusStyle.background} ${statusStyle.text}`}
                      >
                        <span
                          className={`h-1.5 w-1.5 rounded-full ${statusStyle.dot}`}
                        />

                        {report.status}
                      </span>
                    </td>

                    <td className="px-4 py-3">
                      <div className="flex items-center gap-1.5 text-xs font-medium text-[#475467]">
                        <Users className="h-3.5 w-3.5 text-[#98A2B3]" />

                        {report.recipients}
                      </div>
                    </td>

                    <td className="px-4 py-3">
                      <button
                        type="button"
                        onClick={(event) => {
                          event.stopPropagation();

                          onReportClick(
                            report,
                          );
                        }}
                        className="flex h-7 w-7 items-center justify-center rounded-md text-[#98A2B3] opacity-0 transition hover:bg-[#F2F4F7] hover:text-[#344054] group-hover:opacity-100"
                        aria-label={`Open ${report.name}`}
                        title={`Open ${report.name}`}
                      >
                        <MoreHorizontal className="h-4 w-4" />
                      </button>
                    </td>
                  </tr>
                );
              },
            )}
          </tbody>
        </table>
      </div>

      <div className="flex flex-col gap-2 border-t border-[#E4E7EC] bg-[#FCFCFD] px-5 py-3 sm:flex-row sm:items-center sm:justify-between">
        <p className="text-[10px] text-[#667085]">
          Showing{" "}
          <span className="font-semibold text-[#344054]">
            {reports.length}
          </span>{" "}
          report
          {reports.length === 1
            ? ""
            : "s"}
        </p>

        <p className="text-[10px] text-[#98A2B3]">
          Select a report to view details.
        </p>
      </div>
    </div>
  );
}

export default ReportsTable;