import {
  CalendarDays,
  CheckCircle2,
  Download,
  FileBarChart2,
  FileSpreadsheet,
  FileText,
  Pencil,
  Users,
  X,
} from "lucide-react";

import type {
  Report,
} from "../reportsData";

type ReportDetailsProps = {
  report: Report;
  onClose: () => void;
  onEdit: (report: Report) => void;
};

function formatDate(
  value: string,
) {
  return new Intl.DateTimeFormat(
    "en-US",
    {
      month: "short",
      day: "numeric",
      year: "numeric",
    },
  ).format(
    new Date(
      `${value}T00:00:00`,
    ),
  );
}

export function ReportDetails({
  report,
  onClose,
  onEdit,
}: ReportDetailsProps) {
  return (
    <section className="overflow-hidden rounded-xl border border-[#E4E7EC] bg-white shadow-[0_1px_2px_rgba(16,24,40,0.04)]">
      <header className="flex items-center justify-between border-b border-[#E4E7EC] px-5 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#EAF2FF]">
            <FileBarChart2 className="h-4 w-4 text-[#1677FF]" />
          </div>

          <div>
            <p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-[#98A2B3]">
              Report Details
            </p>

            <h2 className="mt-0.5 text-sm font-semibold text-[#172033]">
              {report.name}
            </h2>
          </div>
        </div>

        <button
          type="button"
          onClick={onClose}
          className="flex h-8 w-8 items-center justify-center rounded-lg text-[#667085] transition hover:bg-[#F2F4F7] hover:text-[#172033]"
          aria-label="Close report details"
        >
          <X className="h-4 w-4" />
        </button>
      </header>

      <div className="grid gap-6 p-5 lg:grid-cols-[1.4fr_1fr]">
        <div>
          <div className="mb-5">
            <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
              Description
            </p>

            <p className="mt-1.5 text-xs leading-5 text-[#475467]">
              {report.description}
            </p>
          </div>

          <div className="grid gap-4 sm:grid-cols-2">
            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
                Category
              </p>

              <p className="mt-1 text-xs font-semibold text-[#344054]">
                {report.category}
              </p>
            </div>

            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
                Generated By
              </p>

              <p className="mt-1 text-xs font-semibold text-[#344054]">
                {report.generatedBy}
              </p>
            </div>

            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
                Reporting Period
              </p>

              <div className="mt-1 flex items-center gap-1.5 text-xs font-semibold text-[#344054]">
                <CalendarDays className="h-3.5 w-3.5 text-[#98A2B3]" />

                {formatDate(
                  report.periodStart,
                )}

                <span className="text-[#98A2B3]">
                  —
                </span>

                {formatDate(
                  report.periodEnd,
                )}
              </div>
            </div>

            <div>
              <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
                Records
              </p>

              <p className="mt-1 text-xs font-semibold text-[#344054]">
                {report.records.toLocaleString()}
              </p>
            </div>
          </div>
        </div>

        <div className="rounded-xl border border-[#E4E7EC] bg-[#F9FAFB] p-4">
          <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
            Report Configuration
          </p>

          <div className="mt-4 space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs text-[#667085]">
                Format
              </span>

              <span className="rounded-md bg-white px-2 py-1 text-[10px] font-semibold text-[#475467] ring-1 ring-[#E4E7EC]">
                {report.format}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs text-[#667085]">
                File Size
              </span>

              <span className="text-xs font-semibold text-[#344054]">
                {report.fileSize}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs text-[#667085]">
                Recipients
              </span>

              <span className="flex items-center gap-1 text-xs font-semibold text-[#344054]">
                <Users className="h-3.5 w-3.5 text-[#98A2B3]" />

                {report.recipients}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-xs text-[#667085]">
                Schedule
              </span>

              <span className="text-xs font-semibold text-[#344054]">
                {report.scheduled
                  ? report.schedule ??
                    "Scheduled"
                  : "Manual"}
              </span>
            </div>
          </div>
        </div>
      </div>

      <div className="border-t border-[#E4E7EC] px-5 py-4">
        <p className="text-[10px] font-semibold uppercase tracking-[0.08em] text-[#98A2B3]">
          Included Content
        </p>

        <div className="mt-3 flex flex-wrap gap-2">
          {report.includeSummary && (
            <span className="inline-flex items-center gap-1.5 rounded-md bg-[#E8F8F1] px-2.5 py-1.5 text-[10px] font-semibold text-[#087443]">
              <CheckCircle2 className="h-3 w-3" />
              Executive Summary
            </span>
          )}

          {report.includeCharts && (
            <span className="inline-flex items-center gap-1.5 rounded-md bg-[#EAF2FF] px-2.5 py-1.5 text-[10px] font-semibold text-[#1355B5]">
              <FileBarChart2 className="h-3 w-3" />
              Charts
            </span>
          )}

          {report.includeDetailedData && (
            <span className="inline-flex items-center gap-1.5 rounded-md bg-[#F2F4F7] px-2.5 py-1.5 text-[10px] font-semibold text-[#475467]">
              <FileText className="h-3 w-3" />
              Detailed Data
            </span>
          )}
        </div>
      </div>

      <footer className="flex flex-wrap items-center justify-between gap-3 border-t border-[#E4E7EC] bg-[#FCFCFD] px-5 py-3">
        <div className="text-[10px] text-[#98A2B3]">
          Created {formatDate(report.createdAt)}
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => onEdit(report)}
            className="flex h-8 items-center gap-1.5 rounded-lg border border-[#D0D5DD] bg-white px-3 text-[11px] font-semibold text-[#344054] transition hover:bg-[#F9FAFB]"
          >
            <Pencil className="h-3 w-3" />

            Edit
          </button>

          <button
            type="button"
            disabled={
              report.status !== "Ready"
            }
            className="flex h-8 items-center gap-1.5 rounded-lg bg-[#1677FF] px-3 text-[11px] font-semibold text-white transition hover:bg-[#1264D8] disabled:cursor-not-allowed disabled:bg-[#D0D5DD]"
          >
            {report.format ===
            "Excel" ? (
              <FileSpreadsheet className="h-3 w-3" />
            ) : (
              <Download className="h-3 w-3" />
            )}

            Download
          </button>
        </div>
      </footer>
    </section>
  );
}

export default ReportDetails;